
services:
  db:
    image: postgres
    container_name: Smart
    restart: always
    ports:
      - "55320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1robo1
      POSTGRES_DB: components

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.pl
      PGADMIN_DEFAULT_PASSWORD: admin
