CREATE TABLE orders
(
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    order_status VARCHAR(255),
    order_date   VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);