CREATE TABLE checkout
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    is_ordered BOOLEAN                                 NOT NULL,
    order_id   BIGINT,
    CONSTRAINT pk_checkout PRIMARY KEY (id)
);

ALTER TABLE checkout
    ADD CONSTRAINT FK_CHECKOUT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id);

ALTER TABLE checkout
    ADD CONSTRAINT FK_CHECKOUT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES component (component_id);

ALTER TABLE checkout
    ADD CONSTRAINT FK_CHECKOUT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);