ALTER TABLE checkout
    ADD created TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE orders
    ADD created TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE component
    ADD created TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD created TIMESTAMP WITHOUT TIME ZONE;