ALTER TABLE checkout
    ADD version INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE orders
    ADD version INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE users
    ADD version INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE component
    ADD version INTEGER DEFAULT 0 NOT NULL;